## **BART Projesi**
### Proje Amacı
* Bart istasyonlarla alakalı verileri analiz edip çözüm üreten bir projedir.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

### Verileri Çekip Analize Hazır Etme

In [2]:
import kagglehub
path = kagglehub.dataset_download("saulfuh/bart-ridership")

Downloading to /root/.cache/kagglehub/datasets/saulfuh/bart-ridership/1.archive...

100%|██████████| 49.6M/49.6M [00:00<00:00, 59.4MB/s]

Extracting files...

In [3]:
os.listdir(path)

['station_info.csv',
 'date-hour-soo-dest-2016.csv',
 'date-hour-soo-dest-2017.csv']

In [4]:
df1 = pd.read_csv(os.path.join(path, "date-hour-soo-dest-2016.csv"))
df2 = pd.read_csv(os.path.join(path, "date-hour-soo-dest-2017.csv"))

In [5]:
df1.head()

  Origin Destination  Throughput             DateTime
0   12TH        12TH           1  2016-01-01 00:00:00
1   12TH        16TH           1  2016-01-01 00:00:00
2   12TH        24TH           4  2016-01-01 00:00:00
3   12TH        ASHB           4  2016-01-01 00:00:00
4   12TH        BALB           2  2016-01-01 00:00:00

In [6]:
df1.shape

(9971582, 4)

In [7]:
df1["Origin"].unique()

array(['12TH', '16TH', '19TH', '24TH', 'ASHB', 'BALB', 'BAYF', 'CAST',
       'CIVC', 'COLM', 'COLS', 'CONC', 'DALY', 'DBRK', 'DELN', 'DUBL',
       'EMBR', 'FRMT', 'FTVL', 'GLEN', 'HAYW', 'LAFY', 'LAKE', 'MCAR',
       'MLBR', 'MONT', 'NBRK', 'NCON', 'OAKL', 'ORIN', 'PHIL', 'PITT',
       'PLZA', 'POWL', 'RICH', 'ROCK', 'SANL', 'SBRN', 'SFIA', 'SHAY',
       'SSAN', 'UCTY', 'WCRK', 'WDUB', 'WOAK', 'WSPR'], dtype=object)

In [8]:
df2.head()

  Origin Destination  Throughput             DateTime
0   12TH        19TH           1  2017-01-01 00:00:00
1   12TH        24TH           2  2017-01-01 00:00:00
2   12TH        BAYF           1  2017-01-01 00:00:00
3   12TH        CIVC           5  2017-01-01 00:00:00
4   12TH        COLS           2  2017-01-01 00:00:00

In [9]:
df2.shape

(3313625, 4)

In [10]:
df = pd.concat([df1, df2], axis=0)

In [11]:
df.shape

(13285207, 4)

In [12]:
df_station = pd.read_csv(os.path.join(path,"station_info.csv"))

In [13]:
df_station.head()

,Abbreviation,Description,Location,Name
0,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH)
1,16TH,"2000 Mission Street, San Francisco CA 94110<br...","-122.419694,37.765062,0",16th St. Mission (16TH)
2,19TH,"1900 Broadway, Oakland CA 94612<br />19th Stre...","-122.268602,37.808350,0",19th St. Oakland (19TH)
3,24TH,"2800 Mission Street, San Francisco CA 94110<br...","-122.418143,37.752470,0",24th St. Mission (24TH)
4,ASHB,"3100 Adeline Street, Berkeley CA 94703<br />As...","-122.270062,37.852803,0",Ashby (ASHB)

In [14]:
df_station.shape

(46, 4)

In [15]:
df_main = df.merge(df_station, left_on="Origin", right_on="Abbreviation", how="left")

In [16]:
df_main = df_main.merge(df_station, left_on="Destination", right_on="Abbreviation", how="left", suffixes=('_Origin', '_Destination'))

In [17]:
df_main.head(5)

,Origin,Destination,Throughput,DateTime,Abbreviation_Origin,Description_Origin,Location_Origin,Name_Origin,Abbreviation_Destination,Description_Destination,Location_Destination,Name_Destination
0,12TH,12TH,1,2016-01-01 00:00:00,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH)
1,12TH,16TH,1,2016-01-01 00:00:00,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),16TH,"2000 Mission Street, San Francisco CA 94110<br...","-122.419694,37.765062,0",16th St. Mission (16TH)
2,12TH,24TH,4,2016-01-01 00:00:00,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),24TH,"2800 Mission Street, San Francisco CA 94110<br...","-122.418143,37.752470,0",24th St. Mission (24TH)
3,12TH,ASHB,4,2016-01-01 00:00:00,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),ASHB,"3100 Adeline Street, Berkeley CA 94703<br />As...","-122.270062,37.852803,0",Ashby (ASHB)
4,12TH,BALB,2,2016-01-01 00:00:00,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),BALB,"401 Geneva Avenue, San Francisco CA 94112<br /...","-122.447506,37.721585,0",Balboa Park (BALB)

## Which BART station is the busiest?

In [18]:
Origin_busy = df_main.groupby("Origin")["Throughput"].sum()

In [ ]:
Origin_busy.sort_values(ascending=False)

In [20]:
Origin_busy.idxmax()

'MONT'

In [21]:
Destination_busy = df_main.groupby("Destination")["Throughput"].sum()
Destination_busy.idxmax()

'EMBR'

In [22]:
#Origin_Destination_busy = df_main.groupby(["Origin", "Destination"])["Throughput"].sum().idxmax()

In [23]:
Origin_Destination_busy = Origin_busy.add(Destination_busy, fill_value=0).idxmax()

##### Busiest Station

In [24]:
Origin_Destination_busy

'EMBR'

### What is the least popular BART route?

In [25]:
Bart_route_toplam = df_main.groupby(["Origin", "Destination"])["Throughput"].sum()

In [26]:
Bart_route_min_id = Bart_route_toplam.idxmin()
Bart_route_min_id_val = Bart_route_toplam.min()

In [27]:
print(f"En az popüler rota: {Bart_route_min_id[0]} -> {Bart_route_min_id[1]} (Yolcu sayısı: {Bart_route_min_id_val})")

En az popüler rota: WSPR -> SBRN (Yolcu sayısı: 40)

## When is the best time to go to SF from Berkeley if you want to find a seat?
### Yöntem
* San fransisko ve Berklay ait istasyonları bulmak.
* ondan sonra Berkley'e ait istasyonlardan san faransikoya giden bartın saatlerinin yolcuları bulmak.
* Bunun da toplamını alıp , en düşük olanı koltuk bulmak için en iyi saat olarak belirliyoruz.

In [28]:
df_main["DateTime"] = pd.to_datetime(df_main["DateTime"])
df_main["Saat"] = df_main["DateTime"].dt.hour

In [29]:
sf_istasyonlari = df_main[
    df_main["Description_Origin"].str.contains("San Francisco", na=False)
]["Origin"].unique()

sf_istasyonlari

array(['16TH', '24TH', 'BALB', 'CIVC', 'COLM', 'EMBR', 'GLEN', 'MONT',
       'POWL', 'SFIA', 'SSAN', 'WOAK'], dtype=object)

In [30]:
berklay_istasyonlari = df_main[
    df_main["Description_Origin"].str.contains("Berkeley", na=False)
]["Origin"].unique()
berklay_istasyonlari

array(['ASHB', 'DBRK', 'NBRK', 'PLZA'], dtype=object)

In [31]:
berkley_den_sf = df_main[
    (df_main["Origin"].isin(berklay_istasyonlari)) &
    (df_main["Destination"].isin(sf_istasyonlari))
]
berkley_den_sf.head()

,Origin,Destination,Throughput,DateTime,Abbreviation_Origin,Description_Origin,Location_Origin,Name_Origin,Abbreviation_Destination,Description_Destination,Location_Destination,Name_Destination,Saat
134,ASHB,16TH,4,2016-01-01,ASHB,"3100 Adeline Street, Berkeley CA 94703<br />As...","-122.270062,37.852803,0",Ashby (ASHB),16TH,"2000 Mission Street, San Francisco CA 94110<br...","-122.419694,37.765062,0",16th St. Mission (16TH),0
136,ASHB,CIVC,2,2016-01-01,ASHB,"3100 Adeline Street, Berkeley CA 94703<br />As...","-122.270062,37.852803,0",Ashby (ASHB),CIVC,"1150 Market Street, San Francisco CA 94102<br ...","-122.414123,37.779732,0",Civic Center/UN Plaza (CIVC),0
140,ASHB,EMBR,1,2016-01-01,ASHB,"3100 Adeline Street, Berkeley CA 94703<br />As...","-122.270062,37.852803,0",Ashby (ASHB),EMBR,"298 Market Street, San Francisco CA 94111<br /...","-122.397020,37.792874,0",Embarcadero (EMBR),0
143,ASHB,MONT,1,2016-01-01,ASHB,"3100 Adeline Street, Berkeley CA 94703<br />As...","-122.270062,37.852803,0",Ashby (ASHB),MONT,"598 Market Street, San Francisco CA 94104<br /...","-122.401066,37.789405,0",Montgomery St. (MONT),0
145,ASHB,SFIA,1,2016-01-01,ASHB,"3100 Adeline Street, Berkeley CA 94703<br />As...","-122.270062,37.852803,0",Ashby (ASHB),SFIA,"International Terminal, Level 3, San Francisco...","-122.392409,37.615966,0",San Francisco Int'l Airport (SFIA),0

In [32]:
berkley_den_sf_saat_yolcu = berkley_den_sf.groupby("Saat")["Throughput"]

In [33]:
berkley_den_sf_saat_yolcu.sum().sort_values(ascending=True)

Saat
3         57
2        152
4       5659
1       6091
0      30980
5      47579
23     65348
22     91398
21     98495
20    111059
6     165196
15    205424
19    207147
14    216882
16    220656
13    241273
12    277766
17    314519
11    317140
18    320030
7     439674
10    448847
9     869629
8     872960
Name: Throughput, dtype: int64

* Koltuk bulmak için en iyi saat 24:00. Ama sabah gitmek isterse, sabah 05:00 en muvafık.

## Which day of the week is the busiest?

In [34]:
df_main["Week_day"] = df_main["DateTime"].dt.day_name()

In [35]:
yogun_gun = df_main.groupby("Week_day")["Throughput"].sum().sort_values(ascending=False)

In [36]:
yogun_gun

Week_day
Wednesday    30677189
Tuesday      30350159
Thursday     30049974
Friday       28373709
Monday       26967803
Saturday     13696288
Sunday        9602140
Name: Throughput, dtype: int64

* Çarşamba günü en yoğun gündür.

## How many people take the BART late at night?

In [37]:
bart_late = df_main[df_main["Saat"] >= 22]["Throughput"].sum()

In [38]:
bart_late

np.int64(7049568)

## Compute the straight line distance between every station
### Yönetm
* İlk önce konum verilerden Boylam ve Enlem kordinatları alınır.
* Haversine Förmülü uygulanarak uzaklığı hesaplanır.
#### Haversine Förmülü nedir?
1. Enlem ve Boylam Farkını Bulur: İki istasyon arasındaki yatay (boylam) ve dikey (enlem) uzaklık farkını alır.
2. Dünyanın Eğikliğini Hesaba Katar: Dünya yuvarlak olduğu için kutuplara doğru gidildikçe boylamlar birbirine yaklaşır.
3. Kuş Uçuşu Yayı Hesaplar: İki nokta arasına düz bir cetvel koymak yerine, dünyanın yüzeyi boyunca bükülen eğri yayı hesaplar.
4. Dünyanın Yarıçapı ile Çarpar: Son adımı Dünyanın yarıçapı olan $3956\text{ mil}$ (veya $6371\text{ km}$) ile çarparak sonucu bize gerçek uzunluk birimi olarak verir.
* **Özetle:** İki istasyon arasına yerin altından tünel kazmak yerine, dünya yüzeyi üstünden yürüseydik kaç mil yol giderdik, Haversine tam olarak bunu hesaplar.

In [39]:
df_main["Origin_Longitude"] = df_main["Location_Origin"].str.split(",").str[0].astype(float)

In [40]:
df_main["Origin_Longitude"].values

array([-122.27145, -122.27145, -122.27145, ...,        nan,        nan,
              nan])

In [41]:
df_main["Origin_Latitude"] = df_main["Location_Origin"].str.split(",").str[1].astype(float)

In [42]:
df_main["Origin_Latitude"].values

array([37.803768, 37.803768, 37.803768, ...,       nan,       nan,
             nan])

In [43]:
df_main["Destination_Longitude"] = df_main["Location_Destination"].str.split(",").str[0].astype(float)

In [44]:
df_main["Destination_Longitude"].values

array([-122.27145 , -122.419694, -122.418143, ..., -122.024653,
       -122.160844, -122.057189])

In [45]:
df_main["Destination_Latitude"] = df_main["Location_Destination"].str.split(",").str[1].astype(float)

In [46]:
df_main["Destination_Latitude"].values

array([37.803768, 37.765062, 37.75247 , ..., 38.003193, 37.721947,
       37.634375])

* Haversine förmüle uygulamak için dereceleri radyana çevirilir.

In [47]:
long_or = np.radians(df_main["Origin_Longitude"])
long_dest = np.radians(df_main["Destination_Longitude"])
lat_or = np.radians(df_main["Origin_Latitude"])
lat_dest = np.radians(df_main["Destination_Latitude"])

##### Haversine Förmülü
1. İki istasyon arasındaki yatay (boylam) ve dikey (enlem) uzaklık farkını alır.

In [48]:
dlat = lat_dest - lat_or
dlon = long_dest - long_or

2. Dünyanın eğikliğini hesablanır. Formülün içindeki cos(lat1) * cos(lat2) kısmı, bulunduğun enleme göre bu daralmayı düzeltir.

In [49]:
a = np.sin(dlat / 2) ** 2 + np.cos(lat_or) * np.cos(lat_dest) * np.sin(dlon / 2) ** 2

4. Dünyanın Yarıçapı ile Çarpmak.

In [50]:
df_main["İstasyon_Uzakligi"] = 3956 * (2* np.arcsin(np.sqrt(a)))

In [51]:
df_main[["Origin", "Destination", "İstasyon_Uzakligi"]].drop_duplicates().sort_values(by="İstasyon_Uzakligi", ascending=False).head(10)

     Origin Destination  İstasyon_Uzakligi
3012   MLBR        PITT          37.625136
2827   PITT        MLBR          37.625136
1420   PITT        SFIA          37.001963
724    SFIA        PITT          37.001963
1525   SBRN        PITT          36.779341
4689   PITT        SBRN          36.779341
593    PITT        COLM          36.602121
227    COLM        PITT          36.602121
3054   SSAN        PITT          36.597557
8332   PITT        SSAN          36.597557

### Build a model that can predict the number of people commuting to work by Bart between any 2 stations:
#### 1. How would you approach that?
* ilk önce yolcu sayısını y olarak belirle.
* bazı feature engineering yaparak x'i belirlemek.
* mesala, hafta sonu genelde tatil olduğu için week_day'den cumartesi pazarı çıkarmak.
* istasyon'un yer bilgisini belirlemek. yani ofislere mi yakın,...
* ve geçen haftanın aynı günü ve saatindeki yolcu sayısını belirlemek. Dolayısıyla devamlı işe gidip geleni bulmuş oluruz.
* ondan sonra algo test'e atıp modeli geliştirmek.

### Feature Engineering

In [ ]:
# Weekday'dan Cumartesi ve Pazar günlerini çıkarmak için filtreleme yapıyoruz.
df_weekday = df_main[~df_main["Week_day"].isin(["Saturday", "Sunday"])]

In [54]:
#df_weekday["is_yeri"] = desc_lower.str.contains(r"\b(downtown|center|business|financial|city hall|offices)\b", regex=True).fillna(False).astype(int)

In [55]:
#df_weekday["alisveris_merkezi"] = desc_lower.str.contains(r"\b(shopping|market|shops|mall|restaurants|store)\b", regex=True).fillna(False).astype(int)

In [ ]:
desc_lower = df_station["Description"].str.lower()

In [ ]:
# istasyonların şehir merkezi veya iş yeri olup olmadığını belirlemek için bir sütun ekliyoruz.
df_station["is_yeri"] = desc_lower.str.contains(r"\b(downtown|center|business|financial|city hall|offices)\b", regex=True).fillna(False).astype(int)

/tmp/ipykernel_628/2625342922.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_station["is_yeri"] = desc_lower.str.contains(r"\b(downtown|center|business|financial|city hall|offices)\b", regex=True).fillna(False).astype(int)

In [ ]:
# iş yerine yakın olan istasyonlar
df_station[df_station["is_yeri"] == 1]["Abbreviation"].unique()

array(['12TH', 'BAYF', 'CIVC', 'DBRK', 'EMBR', 'GLEN', 'HAYW', 'LAFY',
       'MONT', 'POWL', 'RICH', 'SBRN', 'WCRK', 'WDUB', 'WOAK'],
      dtype=object)

In [58]:
df_weekday = df_weekday.merge(df_station[["Abbreviation", "is_yeri"]].rename(
    columns={
        "Abbreviation": "Origin",
        "is_yeri": "is_yeri_Origin",
        },

), on="Origin", how="left")

In [59]:
df_weekday = df_weekday.merge(df_station[["Abbreviation", "is_yeri"]].rename(
    columns={
        "Abbreviation": "Destination",
        "is_yeri": "is_yeri_Destination",
        },

), on="Destination", how="left")

In [60]:
df_weekday.head()

,Origin,Destination,Throughput,DateTime,Abbreviation_Origin,Description_Origin,Location_Origin,Name_Origin,Abbreviation_Destination,Description_Destination,...,Name_Destination,Saat,Week_day,Origin_Longitude,Origin_Latitude,Destination_Longitude,Destination_Latitude,İstasyon_Uzakligi,is_yeri_Origin,is_yeri_Destination
0,12TH,12TH,1,2016-01-01,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...",...,12th St. Oakland City Center (12TH),0,Friday,-122.27145,37.803768,-122.271450,37.803768,0.000000,1.0,1.0
1,12TH,16TH,1,2016-01-01,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),16TH,"2000 Mission Street, San Francisco CA 94110<br...",...,16th St. Mission (16TH),0,Friday,-122.27145,37.803768,-122.419694,37.765062,8.519387,1.0,0.0
2,12TH,24TH,4,2016-01-01,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),24TH,"2800 Mission Street, San Francisco CA 94110<br...",...,24th St. Mission (24TH),0,Friday,-122.27145,37.803768,-122.418143,37.752470,8.753948,1.0,0.0
3,12TH,ASHB,4,2016-01-01,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),ASHB,"3100 Adeline Street, Berkeley CA 94703<br />As...",...,Ashby (ASHB),0,Friday,-122.27145,37.803768,-122.270062,37.852803,3.386479,1.0,0.0
4,12TH,BALB,2,2016-01-01,12TH,"1245 Broadway, Oakland CA 94612<br />12th St. ...","-122.271450,37.803768,0",12th St. Oakland City Center (12TH),BALB,"401 Geneva Avenue, San Francisco CA 94112<br /...",...,Balboa Park (BALB),0,Friday,-122.27145,37.803768,-122.447506,37.721585,11.160067,1.0,0.0

* geçen haftanın yolcularını bulmak.

In [61]:
df_weekday = df_weekday.sort_values("DateTime")

In [62]:
## 168  saat 1 hafataya tekabül ettiği için shift(168) yapıyoruz.
df_weekday["1_hafta_onceki_yolcu"] = df_weekday.groupby(["Origin","Destination"])["Throughput"].shift(168)

In [63]:
df_model = df_weekday[["1_hafta_onceki_yolcu","Week_day","Saat","is_yeri_Origin","is_yeri_Destination","Throughput","Origin","Destination"]]

### EDA

In [64]:
df_model.isnull().sum()

1_hafta_onceki_yolcu    353690
Week_day                     0
Saat                         0
is_yeri_Origin           12030
is_yeri_Destination      12973
Throughput                   0
Origin                       0
Destination                  0
dtype: int64

In [65]:
df_model = df_model.dropna(subset=["1_hafta_onceki_yolcu"])

In [66]:
df_model.isnull().sum()

1_hafta_onceki_yolcu       0
Week_day                   0
Saat                       0
is_yeri_Origin          5200
is_yeri_Destination     6145
Throughput                 0
Origin                     0
Destination                0
dtype: int64

In [67]:
df_model["is_yeri_Origin"] = df_model["is_yeri_Origin"].fillna(0)
df_model["is_yeri_Destination"] = df_model["is_yeri_Destination"].fillna(0)

In [68]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9765234 entries, 221984 to 10118923
Data columns (total 8 columns):
 #   Column                Dtype
---  ------                -----
 0   1_hafta_onceki_yolcu  float64
 1   Week_day              object
 2   Saat                  int32
 3   is_yeri_Origin        float64
 4   is_yeri_Destination   float64
 5   Throughput            int64
 6   Origin                object
 7   Destination           object
dtypes: float64(3), int32(1), int64(1), object(3)
memory usage: 633.3+ MB

### Regrasyon Modeli Geliştirme

In [69]:
x = pd.get_dummies(df_model[["1_hafta_onceki_yolcu","Week_day","Saat","is_yeri_Origin","is_yeri_Destination","Origin","Destination"]])
y = df_model["Throughput"]

In [ ]:
#pip install xgboost

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_squared_error

In [72]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.20,random_state=42)

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)

x_test_scaled = scaler.transform(x_test)

In [74]:
xgb=XGBRegressor()
model = xgb.fit(x_train_scaled, y_train)
tahmin = model.predict(x_test_scaled)

In [75]:
r2_score(y_test,tahmin)

0.8336362838745117

In [76]:
mean_squared_error(y_test,tahmin)**.5

15.286282761804065

* "Ashby" istasyonundan "12th St. Oakland" istasyonuna
 Pazartesi sabah 08:00'deki işe gidiş trafiğini tahmin edelim.

In [80]:
yeni_soru = pd.DataFrame(
    [
        {
            "1_hafta_onceki_yolcu":220,
            "Saat": 8,
            "Week_day": "Monday",
            "is_yeri_Origin": 0,  # Ashby (İş yeri değil)
            "is_yeri_Destination": 1,  # 12th St Oakland (İş yeri)
            "Origin": "ASHB",
            "Destination" : "12TH",
        }
    ]
)

yeni_soru = pd.get_dummies(yeni_soru[["1_hafta_onceki_yolcu","Week_day","Saat","is_yeri_Origin","is_yeri_Destination","Origin","Destination"]])

yeni_soru = yeni_soru.reindex(columns=x_train.columns, fill_value=0)

yeni_soru_scale = scaler.transform(yeni_soru)

# Modelden tahmini alıyoruz
tahmin_yolcu_sayisi = model.predict(yeni_soru_scale)
print(f"Tahmini İşe Giden Yolcu Sayısı: {int(tahmin_yolcu_sayisi[0])} kişi")

Tahmini İşe Giden Yolcu Sayısı: 160 kişi

### What additional data would you need?

Modelin daha iyi sonuç verebilmesi için ek verilere ihtiyacımız olabilir.
* Anlık hava durumu. Örneğin Yağış, sıcaklık vb.

* Etkinlik veya resmi tatillerin Verileri.

* Anlık Arıza ve Gecikme Kayıtları.

### How would you want the city or Bart officials to use your data?
* geliştirdiğimiz modelle yoğun saatlerde insanların daha çok iş saatlerinde yoğunluğu azaltılması için daha çok vagonlu veyahut sefer aralıklarını yükseltilmesini ve yoğun olmayan saatlerinde ise daha az sefer aralıkları tavsiye ederim. Böylelikle enerji tasarrufu edebilirler.
* Aynı trafiği yönetebilmeleri için görevlileri ona göre yönderilebilir.
* Hat ve tren bakımları, tahmin edilen yolcu akışının en düşük olduğu zamana denk getirip aksamaları azaltmalarına vesile olabiliriz.